[package]
name = "github-action-test"
version = "0.1.0"
authors = ["yuta-natsume <natsume.yuta@classmethod.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
